apiVersion: v1
kind: Service
metadata:
  name: homecare-backend-service
  labels:
    app: homecare-backend
spec:
  type: LoadBalancer
  selector:
    app: homecare-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
